### ISSUE TITLE
Partials components for big components with variants.

### ISSUE THREAD

**Issue by PhilippeBear** [BearStudio/start-ui-figma#7]
## Is your feature request related to a problem? Please describe.
My problem was that i wanted to override my radius on all my fields. It was painful because I needed to select each input component inside every variants

## Describe the solution you'd like
I was thinking of a way to have a parent component that display the basic design and which will be inherited by all the childs components with variants. Actually it will need to have some slots for the content, but it will be easier to change radius, spaces between elements and colours for fields, buttons, tags etc...

## Additional context
Fields/Partials/Input for the Input component with style.
Fields/Partials/InputContent for the slots values

**Comment by Philippe-Tic** [comment]
This has been done and released for all Inputs 🎉
